language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_69625f6b442b_key -iv $encrypted_69625f6b442b_iv -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
